baseURL = 'https://blog.yenslife.top/' # 記得在 GitHub Pages 上設定 enforce https
locale = 'zh-Hant-TW'
title = '海狸大師部落格'
theme = 'hugo-theme-stack'
DefaultContentLanguage = 'zh-hant-tw'
timeout = '5m'

[languages]
   [languages.en]
     contentDir = 'content/en'
     label = 'English'
     locale = 'en-US'
     weight = 20
     title = "Yenslife's Blog"
   [languages.zh-hant-tw]
     contentDir = 'content/zh-tw'
     label = '台灣正體'
     locale = 'zh-Hant-TW'
     weight = 10
     title = "海狸大師部落格"

[params]
description = "海狸大師部落格，分享學習心得、資安、LLM 等等"
mainSections = [ "post" ]
favicon = "favicon.svg"

[menu]
[[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = -100
    [menu.main.params]
        icon = "home"

[[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/yenslife"
    [menu.social.params]
        icon = "brand-github"

[[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/yenslife"
    [menu.social.params]
        icon = "brand-linkedin"

[[menu.social]]
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.com/@yen_s_life"
    [menu.social.params]
        icon = "brand-youtube"

[[menu.social]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    [menu.social.params]
        icon = "rss"


# 允許在 Markdown 中使用 HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "default"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false # 不能設為 false 才能改一些 code block 的樣式

[params.sidebar]
compact = false
emoji = "🦫"
avatar = "img/avatar.jpg"
subtitle = "太多東西學不完，就姑且放一些碎片在這邊"

[params.widgets]
[[params.widgets.homepage]]
type = "search"
[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 20
[[params.widgets.homepage]]
type = "tag-cloud"
[params.widgets.homepage.params]
limit = 50


[[params.widgets.page]]
type = "search"
[[params.widgets.page]]
type = "toc"
[[params.widgets.page]]
type = "categories"
[[params.widgets.page]]
type = "tag-cloud"

[params.article]
license = { enabled = true }
readingTime = true
math = true

[params.footer]
since = 2025
# customText = "新網站"

# 留言
[params.comments]
enabled = true
provider = "giscus"

# 記得從 giscus.app 取得實際值
[params.comments.giscus]
repo = "yenslife/blog.yenslife.top"
repoID = "R_kgDOQcjOkQ"  
category = "General"     
categoryID = "DIC_kwDOQcjOkc4CzB4C"  
mapping = "pathname"     
strict = true
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "bottom" # 留言框位置
lang = "zh-TW"           # 語言設定
